### ISSUE TITLE
Cant add item

### ISSUE THREAD

**Issue by cyberbug-2077** [Asiern/ReplicantGadget#7]
Hi, i cant add item with this tools. And all information is default like level, platime, etc

**Comment by Asiern** [comment]
Which game version are you using? CODEX?

**Comment by cyberbug-2077** [comment]
> Which game version are you using? CODEX?

steam version 1.0

**Comment by Asiern** [comment]
Latest version of this tool only works with game version 1.0.3.0. If you are running 1.0.0.0 latest Gaget version won't work. If that is your case you could update your game or use one of the old releases: [Gadget-1.0.0](https://github.com/Asiern/ReplicantGadget/releases/tag/1.0.0).
